# Generated by Django 5.2.12 on 2026-03-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuretask',
            name='completion_proof',
            field=models.TextField(blank=True, verbose_name='完成证明'),
        ),
    ]
